### PR TITLE
Various enhancements/fixes

### LINKED ISSUE #6: pam/src: module not FFI-safe
It looks like rust `1.41.0` does not like a few of the `extern` interfaces: (or am I missing something?)
```
warning: `extern` block uses type `std::boxed::Box<module::PamDataT>`, which is not FFI-safe
  --> /home/user/pam-rs/pam/src/module.rs:32:27
   |
32 |                     data: Box<PamDataT>,
   |                           ^^^^^^^^^^^^^ not FFI-safe
   |
   = note: `#[warn(improper_ctypes)]` on by default
   = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
   = note: this struct has unspecified layout

warning: `extern` block uses type `std::boxed::Box<module::PamDataT>`, which is not FFI-safe
  --> /home/user/pam-rs/pam/src/module.rs:33:30
   |
33 |                       cleanup: extern "C" fn(pamh: *const PamHandle,
   |  ______________________________^
34 | |                                            data: Box<PamDataT>,
35 | |                                            error_status: PamResultCode))
   | |_______________________________________________________________________^ not FFI-safe
   |
   = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
   = note: this struct has unspecified layout

warning: functions generic over types or consts must be mangled
  --> /home/user/pam-rs/pam/src/module.rs:55:1
   |
54 |   #[no_mangle]
   |   ------------ help: remove this attribute
55 | / pub extern "C" fn cleanup<T>(_: *const PamHandle, c_data: Box<PamDataT>, _: PamResultCode) {
56 | |     unsafe {
57 | |         let data: Box<T> = mem::transmute(c_data);
58 | |         mem::drop(data);
59 | |     }
60 | | }
   | |_^
   |
   = note: `#[warn(no_mangle_generic_items)]` on by default
```

### PR DESCRIPTION
**Pull request by bossmc**
Sorry this is a bit of a mass of changes, if you're interested in some of these I can break out the individual changes into separate MRs, but I thought I'd send you this to get a conversation rolling.

* Move to 2021 edition (and apply edition idioms)
* Create a workspace so all the crates share compiler caches
    * Required fiddling with the Justfiles in the sample modules since the build output is in a different place now
* Bumped a bunch of dependencies to latest stable releases
* Ensure all FFI objects are FFI-safe (fixes #6)
* Create an `Item` trait that encapsulates "something that can be stored in a PAM item" which handles the conversions from Rust <-> C via raw pointers.
    * This means most items are now represented as `&OsStr` instances in the Rust code (since that's what they are in the C code)
* Fixes for various clippy lints
* Run rustfmt

### CODE REVIEW

File: pam-sober/test.c [hunk 1]
```diff
@@ -23,18 +23,19 @@ int main(int argc, char *argv[]) {
...
 	// Can the accound be used at this time?
 	if (retval == PAM_SUCCESS) {
-		printf("Account is valid.\n");
+		printf("Credentials accepted.\n");
 		retval = pam_acct_mgmt(pamh, 0);
 	}
 
 	// Did everything work?
 	if (retval == PAM_SUCCESS) {
+		printf("Account is valid.\n");
```
Comment (anowell) [inline pam-sober/test.c:38]: It seems a little redundant here to print both "Account is valid." and "Authenticated"

**Review by anowell — APPROVED** [review]
Thanks for this. I don't have a setup currently to actually verify the PAM functionality, so I've basically confirmed it builds and will take your word that it still works.

Separately, I'm adding a github action workflow to help with most of the checks/tests/lints going forward.
